### ISSUE TITLE
¿Cómo se aplica las Modulaciones Digitales ASK, FSK, PSK en sistemas IoT?. ¿Dónde se usa?. Ejemplifique.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea2-grupo-7#5]

**Comment by recursosssbb** [comment]
[Punto_4_Silvana_Barea.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea2-grupo-7/files/11296339/Punto_4_Silvana_Barea.pdf)
