### ISSUE TITLE
¿Qué es el Protocolo HTTP?, ¿Cuáles son sus características? Ejemplifique.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea2-grupo-7#6]

**Comment by recursosssbb** [comment]
[Punto_5_Silvana_Barea.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea2-grupo-7/files/11296378/Punto_5_Silvana_Barea.pdf)
